### ISSUE TITLE
メールマガジンフォームブロックの余白について

### ISSUE THREAD

**Issue by yat8823jp** [wckansai2016/site-design#22]
メールアドレス送信用のフォーム背景の濃いブルー（？）の部分と、下のブロック（セッション公募の告知部分）とに余白が少ないので、今の倍ぐらい開けて欲しい。

**Comment by gouten5010** [comment]
@yat8823jp 
一旦対応しますが、次回更新時（割とすぐ）に募集系のリンクをフロントの上の方に移動させる予定です。メルマガはサイドバーですかね…（検討中）。

**Comment by yat8823jp** [comment]
@gouten5010 

あ、それなら気にせずこのままでいっていいかな。

**Comment by gouten5010** [comment]
ふむ…ならば一旦Closeで。
