### ISSUE TITLE
アクセスページのコーディング

### ISSUE THREAD

**Issue by gouten5010** [wckansai2016/site-design#29]

**Comment by mahirock** [comment]
`<div class="googlemaps">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3275.9679262215677!2d135.4502092509702!3d34.80674878031126!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6000fa7ee36e95fd%3A0x62d1d9fb04184610!2z5aSn6Ziq5aSn5a2mIOWkp-mYquWkp-WtpuS8mumkqA!5e0!3m2!1sja!2sjp!4v1463145063693" width="840" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
<p>会場：大阪大学豊中キャンパス　大阪大学会館</p>
<p>最寄り駅：阪急宝塚線「石橋」、大阪モノレール「柴原」</p>
<h3>阪急宝塚線・石橋駅から会場まで</h3>
<div class="googlemaps">
  <iframe src="https://www.google.com/maps/embed?pb=!1m24!1m8!1m3!1d3275.9417706175554!2d135.4471486!3d34.8074068!3m2!1i1024!2i768!4f13.1!4m13!3e6!4m5!1s0x6000f083641ed811%3A0xe1cdd68f1f86155c!2z55-z5qmL6aeF77yI5aSn6Ziq77yJ!3m2!1d34.808174!2d135.446282!4m5!1s0x6000fa7ee36e95fd%3A0x62d1d9fb04184610!2z44CSNTYwLTAwNDMg5aSn6Ziq5bqc6LGK5Lit5biC5b6F5YW85bGx55S677yR4oiS77yR77yTIOWkp-mYquWkp-WtpiDlpKfpmKrlpKflrabkvJrppKg!3m2!1d34.8067488!2d135.4524033!5e0!3m2!1sja!2sjp!4v1463145351469" width="840" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
<p><a href="http://www.hankyu.co.jp/station/" target="_blank">阪急電鉄路線図</a></p>
<h3>大阪モノレール・柴原駅から会場まで</h3>
<div class="googlemaps">
  <iframe src="https://www.google.com/maps/embed?pb=!1m24!1m8!1m3!1d6552.195298071513!2d135.45136265380987!3d34.80348506794663!3m2!1i1024!2i768!4f13.1!4m13!3e6!4m5!1s0x6000fa859b577391%3A0x44d95930cde5e423!2z5p-05Y6f6aeFLCDlpKfpmKrlupzosYrkuK3luILmn7Tljp_nlLrvvJTkuIHnm64xMTXiiJLvvJE!3m2!1d34.8003706!2d135.4586023!4m5!1s0x6000fa7ee36e95fd%3A0x62d1d9fb04184610!2z44CSNTYwLTAwNDMg5aSn6Ziq5bqc6LGK5Lit5biC5b6F5YW85bGx55S677yR4oiS77yR77yTIOWkp-mYquWkp-WtpiDlpKfpmKrlpKflrabkvJrppKg!3m2!1d34.8067488!2d135.4524033!5e0!3m2!1sja!2sjp!4v1463145438172" width="840" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
<p><a href="http://www.osaka-monorail.co.jp/station/" target="_blank">大阪モノレール路線図</a></p>
<h2>大阪から最寄駅まで</h2>
<p>・阪急宝塚線「梅田」→(約20分)→「石橋」</p>
<h2>新幹線でお越しの方へ</h2>
<p>・JR東海道本線「新大阪」→(約3分)→「大阪」【阪急宝塚線に乗換】「梅田駅」→(約20分)→「石橋」</p>
<h2>飛行機でお越しの方へ</h2>
<h3>大阪国際空港から</h3>
<p>・大阪モノレール「大阪空港」→(約3分)→「柴原」</p>
<h3>関西国際空港から</h3>
<p>・JR関空快速・天王寺行「関西空港」→(約1時間)→「大阪」【阪急宝塚線に乗換】「梅田駅」→(約20分)→「石橋」</p>
<p><a href="http://www.jr-odekake.net/eki/route.html?id=0622602#lat=71.6498329432346&amp;lng=-86.220703125&amp;zl=6" target="_blank">JR路線図</a></p>`

**Comment by ghost** [comment]
@gouten5010 
https://2016.kansai.wordcamp.org/?page_id=573&preview=true

とりあえず去年のをいれました（ガイドさんのURLは切ってます）

**Comment by gouten5010** [comment]
アクセスページの会場・最寄り駅等のSP用デザインが必要。
カンプはなくてもいいので、固定ページ用のフォーマットちゃんと作ったほうがいいかも

**Comment by mahirock** [comment]
@gouten5010 
2014年、2015年のアクセスページを見たのですが、特に特別なデザインにはなっていないようでしたので、「アクセスページの会場・最寄り駅等のSP用デザイン」がどんなものかイメージできていないのですが、どんな感じか教えてもらってもいいですか？
よろしくお願いします。

**Comment by gouten5010** [comment]
@mahirock これは別のissueでもあった、.entry-contentの一番最初の子要素に付与されるpadding-left: 140px; がスマートフォンで見た場合、ちょっとスペース空きすぎに見えるよね問題です。

レスポンシブにした場合、記事タイトルのわぷーの位置や大きさが変更になった際に.entry-contentの一番最初の子要素のpaddingも柔軟に変更して欲しいという要件になります。

現在は冒頭にpタグを挿入することで擬似的に解決していますが、汎用的でない固定ページでは独自のスタイルを当ててやってもいいかなということです。
これはそこまで急ぐものではありませんし、公式テーマ化をする際に汎用的に適用できるようにしたいと思います。

**Comment by gouten5010** [comment]
というわけで　CLOSEしますね。
