### ISSUE TITLE
left: clear; ？

### ISSUE THREAD

**Issue by gouten5010** [wckansai2016/site-design#3]
@mahirock 
dt要素につけているスタイルの中で気になったこと。
`left: clear;`と書かれていますが、これは `clear: left;` の間違いですか？

**Comment by mahirock** [comment]
あ、完全にそれです。
申し訳ないです…

**Comment by gouten5010** [comment]
修正したらこのissueをCloseしておいてください。

**Comment by mahirock** [comment]
やってみます！

**Comment by gouten5010** [comment]
@mahirock 
`clear; left;`になっています。
`clear: left;`に修正してください

**Comment by mahirock** [comment]
修正しました！
