### ISSUE TITLE
バナー配布ページの整形

### ISSUE THREAD

**Issue by gouten5010** [wckansai2016/site-design#45]
去年の流用でOK
https://2015.kansai.wordcamp.org/banner/

**Comment by matsui-a** [comment]
固定ページに、去年のを流し込んでます。
(2015→16に置換しただけで内容はそのままです。）
https://2016.kansai.wordcamp.org/?page_id=580&preview=true

**Comment by matsui-a** [comment]
ページタイトルに続けてh2を置くと、隙間が詰まってしまうようなのですが、どうしましょう...。
マージンの設定を変えるか、画像置くかですかね。

↑（追記）解決してました！

**Comment by spicagraph** [comment]
バナー作成しました。

右カラムに置く用がこちら。
https://2016.kansai.wordcamp.org/files/2016/05/bn-300-190.png

配布用がこちらです。
https://2016.kansai.wordcamp.org/files/2016/05/bnr-234-60.png
https://2016.kansai.wordcamp.org/files/2016/05/bnr-250-250.png
https://2016.kansai.wordcamp.org/files/2016/05/bnr-468-60.png

よろしくお願いします！

**Comment by matsui-a** [comment]
@spicagraph 
ありがとうございます！配布ページに関しては、下書きで反映しました。
一つ気になったのですが、250-250.pngの上に線が無いのってこれであってますでしょうか..?
