### ISSUE TITLE
メニュー展開時、ネストがある場合に展開するためのボタンが、↓のところしかタップできない

### ISSUE THREAD

**Issue by yat8823jp** [wckansai2016/site-design#55]
親テーマの仕様かもしれませんが、メニューがネストしている場合、展開させるのにボタン全体ではなく、↓のボタンしか反応しないので、ここを対応したい。
親テーマの仕様で変更できない場合はわかるようにデザインを修正するので連絡くだされば。

**Comment by gouten5010** [comment]
@yat8823jp 確認後実装検討します

**Comment by gouten5010** [comment]
@yat8823jp これ考えたんですけど、ネストがある場合、展開させるのにボタン全体をタップできるようにすると親メニューにリンクがある時に、リンク効かなくなりますね。
なので以下のいずれかの対処が必要かと思われます。
- 親メニューのリンクは必ず空にする
- ネストした時の▼リンクをもっと分かりやすいデザインにする
- 放置

**Comment by yat8823jp** [comment]
@gouten5010 あ、じゃあ右側の領域をボタンぽくあしらうデザインに変更しましょう。デザインやりますー

**Comment by gouten5010** [comment]
@yat8823jp オネシャスー。

**Comment by gouten5010** [comment]
@matsui-a https://wckansai2016.slack.com/files/yat/F1B6RF5G9/sm_index.jpg
ここに画像ありますので継続で対応お願いします。
