### ISSUE TITLE
お問い合わせフォームページのコンテンツが左に凝縮されている

### ISSUE THREAD

**Issue by yat8823jp** [wckansai2016/site-design#56]
フォームページのコンテンツが短くなっているので、修正が必要。

**Comment by gouten5010** [comment]
@yat8823jp これ今のデザインを元にリデザインできないかな？
YATさんじゃなくてもいいので。

**Comment by mahirock** [comment]
@gouten5010 
とりあえず、原因はentry-titleのわぷーのためにつけてる
`.entry-content>:first-child {
    padding-right: 140px;
}`
これのいたずらだったため、固定ページの投稿画面にて、一番トップに
`<p></p>`
挿入しましたが…

実行委員一覧ページにも影響しているこのスタイルをどうするかの検討が必要かと…

**Comment by mahirock** [comment]
いったん暫定処置にて対応。
closeします。
