### ISSUE TITLE
グローバルメニューの左側にある雲の端っこが切れている

### ISSUE THREAD

**Issue by yat8823jp** [wckansai2016/site-design#57]
左側の雲が切れてるので、修正が必要。

**Comment by yat8823jp** [comment]
![image](https://cloud.githubusercontent.com/assets/1327196/15379752/404ab0c8-1dab-11e6-9918-21c783346d10.jpg)

**Comment by gouten5010** [comment]
@yat8823jp カンプがすでにそういう仕様だった

![2016-05-25 23 23 32](https://cloud.githubusercontent.com/assets/3461188/15543418/c8ef1c06-22cf-11e6-9fad-784958c03eec.png)
