### ISSUE TITLE
カテゴリメニューのデザインが少し違う

### ISSUE THREAD

**Issue by yat8823jp** [wckansai2016/site-design#58]
・周りにボーダーが必要（他のウィジェットとの統一感）
・最下部にシャドウ（議論があったと思うので、デザイン変更の必要があれば相談で。）
の対応お願いします。

**Comment by gouten5010** [comment]
@yat8823jp これはデザイン変更をするか時間をもらうかのどちらかで判断したいです。

**Comment by yat8823jp** [comment]
シャドウのことかな？
ボーダーはどうだろう？

**Comment by gouten5010** [comment]
ボーダーは対応できるね。
先にボーダー対応しましょう
