### ISSUE TITLE
背景の空が右にずれている

### ISSUE THREAD

**Issue by yat8823jp** [wckansai2016/site-design#61]
背景が右にずれているので調整が必要。

**Comment by gouten5010** [comment]
@yat8823jp 切り出しの問題かなあ？ @mahirock ねえ？

**Comment by mahirock** [comment]
@gouten5010 
言われてみれば切り出し段階でちょっと左の白い部分の方が多いような…

![2016-05-19 16 36 19](https://cloud.githubusercontent.com/assets/15726918/15385951/ea4e6252-1ddf-11e6-887a-288cfccd872a.png)

**Comment by gouten5010** [comment]
@mahirock カンプの中心に合わせて再度切り出しお願いします。
