### ISSUE TITLE
メニューとコンテンツの間がせまい

### ISSUE THREAD

**Issue by gouten5010** [wckansai2016/site-design#63]
またはコンテンツとサイドバーの間が広い。
要はカンプと違うということ。

<img width="1478" alt="2016-05-19 11 04 48" src="https://cloud.githubusercontent.com/assets/3461188/15380458/9eb28f54-1db1-11e6-827e-813656ff2b75.png">

**Comment by mahirock** [comment]
対応します

**Comment by gouten5010** [comment]
@mahirock 
なぜスマートフォンでの表示まで修正したのですか？
要件に入っていない上にカンプと違うスタイルになっているのですが。

![2016-05-19 22 12 34](https://cloud.githubusercontent.com/assets/3461188/15394651/122bc4ca-1e0f-11e6-8bbb-45f942610804.png)
