### ISSUE TITLE
実行委員紹介が全体右に余白ができてる

### ISSUE THREAD

**Issue by ghost** [wckansai2016/site-design#65]
https://2016.kansai.wordcamp.org/organizers/

ページ自体が若干左に寄ってる？

**Comment by gouten5010** [comment]
@mellowchanter ページ全体、ではなく、`.entry-content` の子要素のうち、最初の要素だけ右にpaddingが出るようにしていますので、これが影響しているようです。
これはアイキャッチがない記事の場合に見出しのわぷーがテキストと被ってしまうのを回避する処置だったのですが、個別記事だけに限定したほうが良さそうですね。
