### ISSUE TITLE
Twitterのog:imageが出てこない

### ISSUE THREAD

**Issue by matsui-a** [wckansai2016/site-design#74]
[Twitter](https://twitter.com/wckansai2016)の画像が出てないようです。
（Facebookは大丈夫でした）
原因調査してないですが、og:imageに設定されてる画像が重いからとか関係あります？

**Comment by gouten5010** [comment]
@matsui-a 関係ありそうですね。
Twitter Card Validatorでも同様の現象が起こります
https://cards-dev.twitter.com/validator

もともとアイキャッチをメインビジュアルのヘッダーにしようしていたので横幅4000pxのがアップされてるんですね。
いまはアイキャッチ設定しても隠す仕様にしているので、差し替えてもいいですね。

ご指摘ありがとうございます。

**Comment by gouten5010** [comment]
@matsui-a 画像差し替えました。
一応 Twitter Card Validator で確認したのですが、松井さんのほうで確認の手段等はありますか？
確認できたらこのissueをcloseしてください。
問題がある場合はコメントください。

**Comment by matsui-a** [comment]
対応ありがとうございます！
画像、表示されました！
