### ISSUE TITLE
メインビジュアル画像重くないです...?

### ISSUE THREAD

**Issue by matsui-a** [wckansai2016/site-design#75]
表示されるのが重いような気がしたので。
（うちのネット環境が重いだけだったらすいません。）

**Comment by gouten5010** [comment]
@matsui-a 重いです。もともとのファイルが重いのが原因ということもあるので、今後レイヤーを分けて背景に関しては分からない程度に色数を削減するとかヘッダ情報を削除するとかしたいと思っています。

**Comment by gouten5010** [comment]
こちらに関しては #69 で対応する予定です。

**Comment by torounit** [comment]
png -> jpg にするだけでも結構違いそうですね。

**Comment by matsui-a** [comment]
確かに、この画像であればjpgでよさそうですね。

**Comment by gouten5010** [comment]
このissueでjpgにしとこ

**Comment by gouten5010** [comment]
@matsui-a jpgにしてアップデートしましたがどうでしょう？
大丈夫そうならcloseしてください

**Comment by matsui-a** [comment]
確認しました！半分くらい軽くなってますね！
対応ありがとうございます。
