### ISSUE TITLE
メタボックスのオブジェクト位置が左にずれている

### ISSUE THREAD

**Issue by gouten5010** [wckansai2016/site-design#84]
直したはずなんだけどなあ( ˘ω˘)

![2016-05-23 22 45 19](https://cloud.githubusercontent.com/assets/3461188/15473075/24f6f336-2139-11e6-81fb-2a0bf9810104.png)

**Comment by matsui-a** [comment]
「記事詳細 」はいけてますが、「ブログ一覧」の方がいけてないようですね。
表示されてないauthor画像を出すべく、`.byline` を`display: inline`したらいけますが、そうすると`.comments-link`も出てきてしまいました...

![comment](https://cloud.githubusercontent.com/assets/1404480/15592496/3ee0c378-23df-11e6-8db3-b744ae9ccb5a.png)
.comments-link を display: none; してもいいもんですかね。

**Comment by matsui-a** [comment]
と、思ってデザインみたら、そもそもデザインがまだ反映されてなかったようなので、メタボックスの他の要素もちょっといじりますね。
