### ISSUE TITLE
番号付きリストタグ

### ISSUE THREAD

**Issue by gouten5010** [wckansai2016/site-design#94]
#60 の派生。

番号付きのリストのスタイルの見落とし。

![2016-05-26 21 35 24](https://cloud.githubusercontent.com/assets/3461188/15574711/f3b25dd0-2389-11e6-8be2-632b08f8b0a9.png)

マークアップサンプルとはいったい…うごごごご
https://2016.kansai.wordcamp.org/styleguide/

**Comment by matsui-a** [comment]
引用コンテンツ が 左にでしゃばってるのも個人的には気になりますがどうです...?

**Comment by gouten5010** [comment]
@matsui-a 全体的に気なる箇所はあります。マークアップサンプルでデザイン適用漏れ、多いですね(´・ω・｀)
